/**
 * The command reference is generated from the command tree, so a flag that
 * exists in code cannot be missing from the docs. `docs --check` keeps the
 * committed file honest in CI.
 */
import type { Command } from '../ctx.ts'
import { ZH, ZH_GLOBAL, type ZhEntry } from './zh.ts'

export type Lang = 'en' | 'zh'

const T = {
  en: {
    title: '# Command reference',
    intro: 'Generated by `storeship docs` from the command definitions — do not edit by hand. Every command accepts the global flags. Positional arguments are in `<>`; optional parts in `[]`.',
    global: '## Global flags',
    flags: 'Flags',
    inherited: 'inherited from',
    sub: 'Subcommands',
    usage: 'Usage',
    impact: 'Impact',
    needs: 'needs',
    human: 'The human decides',
    irreversible: 'Irreversible',
    words: { read: 'read — changes nothing', write: 'write', irreversible: 'irreversible — refuses to run without `--yes`' } as Record<string, string>,
  },
  zh: {
    title: '# 命令参考',
    intro: '由 `storeship docs --lang zh` 从命令定义生成，不要手改。所有命令都接受全局参数。`<>` 是必填位置参数，`[]` 是可选部分。',
    global: '## 全局参数',
    flags: '参数',
    inherited: '继承自',
    sub: '子命令',
    usage: '用法',
    impact: '影响面',
    needs: '依赖',
    human: '由人决定',
    irreversible: '不可撤销',
    words: { read: '只读 —— 什么都不改', write: '会写', irreversible: '不可撤销 —— 不给 `--yes` 就拒绝执行' } as Record<string, string>,
  },
}

const esc = (s: string): string => s.replace(/\|/g, '\\|')

function text(path: string, cmd: Command, lang: Lang): { summary: string; flags: Record<string, string>; human: string[] } {
  const zh: ZhEntry | undefined = lang === 'zh' ? ZH[path] : undefined
  const flags: Record<string, string> = {}
  for (const [k, v] of Object.entries(cmd.flags ?? {})) flags[k] = zh?.flags?.[k] ?? v
  return { summary: zh?.summary ?? cmd.summary, flags, human: zh?.human ?? cmd.humanDecisions ?? [] }
}

function flagTable(flags: Record<string, string>, t: (typeof T)['en']): string[] {
  const names = Object.keys(flags)
  if (!names.length) return []
  return ['', `| ${t.flags} | |`, '|---|---|', ...names.map((n) => `| \`--${n}\` | ${esc(flags[n]!)} |`)]
}

function section(cmd: Command, path: string[], depth: number, lang: Lang, inherited: { from: string; flags: Record<string, string> }[]): string[] {
  const t = T[lang]
  const key = path.join(' ')
  const { summary, flags, human } = text(key, cmd, lang)
  const out = ['', `${'#'.repeat(depth)} \`${key}\``, '', summary]
  if (cmd.usage || !cmd.sub) out.push('', `${t.usage}: \`storeship ${cmd.usage ?? key}\``)
  const impact = cmd.impact ?? 'read'
  out.push('', `${t.impact}: ${t.words[impact]}${cmd.needs?.length ? ` · ${t.needs}: ${cmd.needs.join(', ')}` : ''}`)
  if (cmd.confirm) out.push('', `${t.irreversible}: ${esc(cmd.confirm)}`)
  if (human.length) out.push('', `${t.human}: ${human.map(esc).join('; ')}`)
  out.push(...flagTable(flags, t))
  for (const inh of inherited) if (Object.keys(inh.flags).length) out.push('', `${t.flags} (${t.inherited} \`${inh.from}\`):`, ...flagTable(inh.flags, t).slice(1))
  if (cmd.sub) {
    out.push('', `${t.sub}: ${cmd.sub.map((s) => `[\`${s.name}\`](#${[...path, s.name].join('-')})`).join(' · ')}`)
    const nextInherited = Object.keys(flags).length ? [...inherited, { from: key, flags }] : inherited
    for (const s of cmd.sub) out.push(...section(s, [...path, s.name], depth + 1, lang, nextInherited))
  }
  return out
}

export function renderCommandDocs(commands: Command[], globalFlags: Record<string, string>, lang: Lang): string {
  const t = T[lang]
  const g = lang === 'zh' ? { ...globalFlags, ...ZH_GLOBAL } : globalFlags
  const lines = [t.title, '', t.intro, '', t.global, ...flagTable(g, t).slice(1), '', '## ' + (lang === 'zh' ? '命令' : 'Commands'), '']
  lines.push(...commands.map((c) => `- [\`${c.name}\`](#${c.name}) — ${text(c.name, c, lang).summary}`))
  for (const c of commands) lines.push(...section(c, [c.name], 2, lang, []))
  return lines.join('\n') + '\n'
}
