/** Library surface: the same functions the CLI calls, for scripts and agents that prefer code. */
export { createClient, signJwt, explain, ok, AscError, type AscClient, type AscResult } from './asc/client.ts'
export * from './asc/versions.ts'
export * from './asc/listing.ts'
export * from './asc/media.ts'
export * from './asc/misc.ts'
export * from './asc/offers.ts'
export * from './asc/analytics.ts'
export * from './ios/xcode.ts'
export { loadConfig, resolveConfig, findConfigFile, defaultKeyPath, type Config, type RawConfig } from './config.ts'
export { StoreshipError, UsageError, ConfigError } from './errors.ts'
export { HINTS, hintFor } from './hints.ts'
export * from './shots/types.ts'
export { DEVICES, PREVIEW_TYPE, mergeDevices } from './shots/devices.ts'
export { checkShots, stemOf } from './shots/check.ts'
export { pngSize, findChrome, shoot, sheet, renderShot } from './shots/render.ts'
export { defaultTemplate } from './shots/defaultTemplate.ts'
export { loadShots } from './shots/load.ts'
export { uploadShots } from './shots/upload.ts'
export { Sim, findIdb, bootedUdid } from './sim/sim.ts'
export { findFfmpeg, probe, parseProbe, parseDuration } from './preview/ffmpeg.ts'
export { cutPreview, parseSegment, xfadeChain } from './preview/cut.ts'
export { checkPreview, defaultSize, PREVIEW_SIZES } from './preview/specs.ts'
export { startRecording, stopRecording } from './preview/record.ts'
